eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**

        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**

        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**
<<<<<<< HEAD
        
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**


=======
>>>>>>> f514b8771bd7e6f7ca5a275cf6d41d524758c453
