server:
  port: 8000
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://service-one
          predicates:
            - Path=/order/**

        - id: inventory
          uri: lb://service-two
          predicates:
            - Path=/inventory/**

      default-filters:
        - RewritePath=/service-(?<segment>.*)/(?<path>.*), /${path}
