eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**

        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**

        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**
        
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**

        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**
