eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
spring:  
    security:
      recaptcha:
        verifyUrl: https://www.google.com/recaptcha/api/siteverify
        secretKey: mgxkYkMW829scNrW8AzGLqG1xFQFFkeLdvdvv23423432bbrgtbtrgb@q$%er
      jwt:
        secret-key: mgxkYkMW829scNrW8AzGLqG1xFQFFkeLdvdvv23423432bbrgtbtrgb342423
        token-expiration:
          access: 600000
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/supermarket
  jpa:
    hibernate:
      ddl-auto: update
