server:
  port: 8070
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    username: local
    password: local
    url: local
  jpa:
    hibernate:
      ddl-auto: update
