server:
  port: 8070

spring:
  profiles:
    active: dev
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# spring:
#   datasource:
#     username: postgres
#     password: admin
#     url: jdbc:postgresql://localhost:5432/supermarket
#   jpa:
#     hibernate:
#       ddl-auto: update
