server:
  port: 8090
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9090
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3  # Limit retries to 3
      properties:
        delivery.timeout.ms: 30000  # Total time allowed for retries
        request.timeout.ms: 5000
    topic:
      new_order: new_order
      fail_order: fail_order
