server:
  port: 8090
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  kafka:
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer     
    topic:
      new_order: new_order
      fail_order: fail_order
