spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/supermarket
  kafka:
    producer:
      bootstrap-servers: localhost:9090
  jpa:
    hibernate:
      ddl-auto: update
